CREATE TABLE `PRODUCT` (
  `PROD_ID` int(8) unsigned NOT NULL,
  `VEND_ID` int(9) unsigned NOT NULL,
  `PROD_DESCRIPT` varchar(200) NOT NULL,
  `PROD_TITLE` varchar(50) NOT NULL,
  `PROD_TYPE` char(1) NOT NULL,
  `PROD_COST` int(8) NOT NULL,
  `STORAGE_INSTRUCT` varchar(200) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;


CREATE TABLE `VENDOR` (
  `VEND_ID` int(8) unsigned NOT NULL,
  `VEND_NAME` varchar(50) NOT NULL,
  `VEND_BALANCE` decimal(8,2) unsigned NOT NULL,
  `VEND_CONTACT_PHONE` varchar(15) NOT NULL,
  `VEND_CONTACT_EMAIL` varchar(50) NOT NULL,
  `VEND_CONTACT_NAME` varchar(50) NOT NULL,
  `VEND_JOIN_DATE` date NOT NULL,
  `VEND_IN_BUISNESS` tinyint(1) NOT NULL,
  `VEND_ADDRESS` varchar(50) NOT NULL,
  PRIMARY KEY (`VEND_ID`),
  UNIQUE KEY `VEND_CONTACT_NAME` (`VEND_CONTACT_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE `COLD_GOOD` (
  `PROD_ID` int(8) unsigned NOT NULL,
  `STORAGE_TEMP` decimal(6,2) NOT NULL,
  `EXP_TYPE` varchar(15) DEFAULT NULL,
  `SHELF_LIFE` varchar(30) DEFAULT NULL,
  `PERISH_INSTRUCT` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`PROD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE `STABLE` (
  `PROD_ID` int(8) unsigned NOT NULL,
  `SHELF_LIFE` varchar(50) DEFAULT NULL,
  `TEMP_RANGE` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`PROD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE `HAZARDOUS` (
  `PROD_ID` int(8) unsigned NOT NULL,
  `HAZARD_TYPE` varchar(15) DEFAULT NULL,
  `HAZARD_DESCRIPT` varchar(200) DEFAULT NULL,
  `HAZARD_INSTRUCT` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`PROD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE `CUSTOMER` (
  `CUST_ID` int(8) unsigned NOT NULL AUTO_INCREMENT,
  `CUST_DELIV_ADDRESS` varchar(50) NOT NULL,
  `CUST_BALANCE` decimal(8,2) DEFAULT NULL,
  `CUST_IS_ORG` tinyint(1) NOT NULL,
  `CUST_PHONE` varchar(15) DEFAULT NULL,
  PRIMARY KEY (`CUST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE `DAILY_INVENTORY` (
  `PROD_ID` int(8) unsigned NOT NULL,
  `INV_DATE` date NOT NULL,
  `PRODUCT_STUCK` int(8) unsigned DEFAULT NULL,
  `PRODUCT_INCOMING` int(8) unsigned DEFAULT NULL,
  PRIMARY KEY (`PROD_ID`,`INV_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE `INVOICE` (
  `CUST_ID` int(8) unsigned DEFAULT NULL,
  `INV_NUM` int(8) unsigned NOT NULL AUTO_INCREMENT,
  `V_DATE` date NOT NULL,
  `INV_STATUS` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`INV_NUM`,`V_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE `LINE` (
  `INV_NUM` int(8) unsigned NOT NULL,
  `V_DATE` date NOT NULL,
  `PROD_ID` int(8) unsigned NOT NULL,
  `PROD_COUNT` int(8) unsigned DEFAULT NULL,
  `TOTAL_COST` decimal(8,2) DEFAULT NULL,
  `PROD_COST` decimal(8,2) DEFAULT NULL,
  `TAX_EXEMPT` tinyint(1) DEFAULT 0,
  PRIMARY KEY (`INV_NUM`,`V_DATE`,`PROD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE `ORGANIZATION` (
  `CUST_ID` int(8) unsigned NOT NULL,
  `ORG_CONTACT_NAME` varchar(50) DEFAULT NULL,
  `ORG_TYPE` varchar(50) DEFAULT NULL,
  `ORG_JOIN_DATE` date DEFAULT NULL,
  `ORG_DESCRIPT` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`CUST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE `PERSONAL` (
  `CUST_ID` int(8) unsigned NOT NULL,
  `CUST_FNAME` varchar(50) DEFAULT NULL,
  `CUST_LNAME` varchar(50) DEFAULT NULL,
  `CUST_M_INITAL` char(1) DEFAULT NULL,
  `SHIPPING_TYPE` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`CUST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE `SHIPPER` (
  `SHIPPER_ID` int(8) unsigned NOT NULL AUTO_INCREMENT,
  `SHIPPER_NAME` varchar(15) DEFAULT NULL,
  `SHIPPER_JOIN_DATE` date DEFAULT NULL,
  `SHIPPER_BALANCE` decimal(8,2) DEFAULT NULL,
  `SHIPPER_CONTACT_PHONE` varchar(15) DEFAULT NULL,
  `SHIPPER_CONTACT_NAME` varchar(50) DEFAULT NULL,
  `SHIPPER_CONTACT_EMAIL` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`SHIPPER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE `SHIPMENT` (
  `SHIPPER_ID` int(8) unsigned DEFAULT NULL,
  `SHIP_ID` int(8) unsigned NOT NULL,
  `SHIP_DATE` date NOT NULL,
  `SHIP_STATUS` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`SHIP_ID`,`SHIP_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE `SHIP_LINE` (
  `SHIP_ID` int(8) unsigned NOT NULL,
  `PROD_ID` int(8) unsigned NOT NULL,
  `PROD_COUNT` int(8) unsigned NOT NULL,
  `TOTAL_COST` decimal(8,2) NOT NULL,
  PRIMARY KEY (`SHIP_ID`,`PROD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;